### ISSUE TITLE
Invisible stacks and Error executing task java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by utoc** [primetoxinz/StacksOnStacks#10]
We don't get a crash but instead stackOnStacks stacks are.. invisible and it looks like any ingots we lay down are eaten.  I don't have a lot to go on but I'll give you what I can. 

Paste here: http://pastebin.com/FRi1n5HV

Screenshot here (Featuring negative items): http://imgur.com/a/OiEXb

All that was done was placing an iron ingot on the ground.  In this case the ingot was not eaten.

StacksOnStacks2-1.1.0
forge-1.10.2-12.18.1.2011
on Minecraft 1.10.2

Please let me know any way I can help you do additional basic troubleshooting

**Comment by primetoxinz** [comment]
Know the issue, attempting to fix now

**Comment by primetoxinz** [comment]
new version will be on curse any minute now

**Comment by utoc** [comment]
One miscellaneous question: Is there anyway to blacklist a certain block from being stack'ed upon?  Botania's runic alter wants to stack Mana Steel.  Its no big deal because I can hit Q to drop the item onto the altar rather than try to right click.  Should I open a new ticket?

**Comment by primetoxinz** [comment]
no need for a ticket, I'll do that right now

**Comment by primetoxinz** [comment]
I'll just make it not work on tile entities

**Comment by utoc** [comment]
Tested, no crash (except from one user but his crashing stopped when he removed Optifine).  Also, as you stated, this will no longer place ingots on TEs.  Thanks for that quick fix.

I am getting this on the server log:

```
> false
[14:31:43] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Vector3f
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Vector3f
        at com.primetoxinz.stacksonstacks.ingot.IngotLocation.getRelativeLocation(IngotLocation.java:60) ~[IngotLocation.class:?]
        at com.primetoxinz.stacksonstacks.ingot.PartIngot.onActivated(PartIngot.java:218) ~[PartIngot.class:?]
        at mcmultipart.multipart.MultipartContainer.onActivated(MultipartContainer.java:369) ~[MultipartContainer.class:?]
        at mcmultipart.block.BlockMultipartContainer.func_180639_a(BlockMultipartContainer.java:184) ~[BlockMultipartContainer.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more

```

only when I stack on top of an existing placed ingot as console spam.  So if I place 8 gold ingots in one rectangle, I will get the above message 7 times.

**Comment by primetoxinz** [comment]
ok, should be fixed. uploading to curse. next time make a new issue

**Comment by utoc** [comment]
Will do.  Tested, working as intended. Thanks

**Comment by primetoxinz** [comment]
awesome
